version: "3"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5600:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - dev

networks:
  dev: